#https://pre-commit.com/hooks.html
repos:

  # Code Formatter
-   repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
    - id: black
      language_version: python3.8
      stages: [commit]

  # Lintter
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies: [flake8-docstrings]
      stages: [commit]

  # Tests
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        args: [-s, -v, -vv, --durations=0, --cache-clear]
        language: system
        always_run: true
        verbose: true
        pass_filenames: false
        stages: [push]